server:
  servlet:
    context-path: /api

kwops:
  message:
    topicexchangename: x.kwops
    queuename: q.devops-register-team
    routingkey: k.kwops-devops

spring:
  datasource:
    url: jdbc:mysql://jsk3f4rbvp8ayd7w.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/dwiywi92ai4ci2au
    username: ec11d6dkq4rsd0af
    password: f3s8669l2189nonn
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: uphomszs
    password: SCWM9Il4GJuGcS9LxGxmKvrfXoBIHSxS
    virtual-host: uphomszs
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kwops.eu.auth0.com/
          audiences: https://kwops-api/
