server:
  servlet:
    context-path: /api
  port: 8082

kwops:
  message:
    topicexchangename: x.kwops
    queuename: q.devops-register-team
    routingkey: k.kwops-devops

spring:
  datasource:
    url: jdbc:mysql://b4e9xxkxnpu2v96i.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/fii6keqiojtsjgpr
    username: ojhkivy8fm2bivnf
    password: y2kdr6ibs4csferf
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: uphomszs
    password: SCWM9Il4GJuGcS9LxGxmKvrfXoBIHSxS
    virtual-host: uphomszs
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2