name: Workflow to build, test, and upload coverage to Codecov
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Install dependencies, run tests, and collect coverage
        run: gradle build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Run devops bootJar with Gradle Wrapper
        run: ./gradlew :devops:bootJar
      - name: Change to correct dir
        run: cd devops && ls
#      - name: make heroku-deployer executable
#        run: chmod +x ./heroku-deployer.jar
      - name: Run hr bootJar with deploy task
        working-directory: devops
        run: HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} java -jar ./heroku-deployer.jar -a kwops-devops build/libs/devops-0.0.1-SNAPSHOT.jar

