name: Workflow to build, test, and upload coverage to Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Install dependencies, run tests, and collect coverage
        run: gradle build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
